### ISSUE TITLE
Buggy Character Movement Nodes

### ISSUE THREAD

**Issue by agent-q1** [Terasology/Pathfinding#48]
# Buggy Character Movement

Even though pathfinding has had improvements, and seems fairly stable at the point, the main issue with in game pathfinding, is actually moving along the path. Even fundamental nodes such as the MoveToAction node that pretty much all pathfinding behaviors use/depend on seem buggy. These lead to a plethora of quirks in game well described by https://github.com/Terasology/Behaviors/issues/20 

Vaguely remember kaen and I discussing how the prediction systems and delta values might having something to do with the glitch, so the Character Prediction System should be a good starting point. Could also have something to do with CPU usage.
There could also be a bug in kinematic character, specifically with the code dealing with extrapolation leading to all kinds of funny behavior.

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
